// Model screen: run one candidate through the gate world with shipped default prompts, score the objective
// axes, and emit a one-page card + append to a deduped leaderboard. Prose quality is left as a slot for an
// in-session Claude read (or a future --judge flag) — the auto axes need no judge.
//
// Usage:  node screen.mjs --model <label> [--no-run] [--file <dump.json>]
//   --model    model label as it appears in profiles.json (required)
//   --no-run   skip the baseline run; score the newest existing screen-<label> dump
//   --file     score a specific dump file instead of running / searching

import { spawn } from "node:child_process";
import { readFileSync, writeFileSync, readdirSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { scoreDump } from "./screenScore.mjs";

const HARNESS_DIR = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(HARNESS_DIR, "../../..");
const RUNS_DIR = path.resolve(HARNESS_DIR, "../runs");
const BOARD_JSON = path.resolve(HARNESS_DIR, "../leaderboard.json");
const BOARD_MD = path.resolve(HARNESS_DIR, "../leaderboard.md");

const args = process.argv.slice(2);
const argVal = (f) => { const i = args.indexOf(f); return i >= 0 ? args[i + 1] : null; };
const model = argVal("--model");
const noRun = args.includes("--no-run");
const fileArg = argVal("--file");
if (!model) { console.error("screen.mjs: --model <label> is required"); process.exit(1); }

const bar = (pct) => { const n = Math.round(pct / 20); return "▓".repeat(n) + "░".repeat(5 - n); };

function runBaseline() {
  return new Promise((resolve, reject) => {
    const started = Date.now();
    console.log(`▶ screening ${model} — running gate world (shipped prompts)…`);
    const child = spawn("node", [path.join(HARNESS_DIR, "run.mjs"), "--profile", "screen", "--model", model],
      { cwd: REPO_ROOT, shell: false, stdio: "inherit" });
    child.on("exit", (code) => code === 0 ? resolve(Date.now() - started) : reject(new Error(`run.mjs exited ${code}`)));
    child.on("error", reject);
  });
}

function newestDump() {
  const safe = model.replace(/[^a-z0-9-]/gi, "-");
  const files = readdirSync(RUNS_DIR).filter((f) => f.startsWith(`screen-${safe}-`) || f.startsWith(`screen-${model}-`));
  if (!files.length) throw new Error(`no screen-${model} dump in ${RUNS_DIR} — run without --no-run first`);
  return path.join(RUNS_DIR, files.sort().at(-1));
}

const score = (dump) => scoreDump(JSON.parse(readFileSync(dump, "utf8")));

function card(s, latencyMs) {
  const dateStr = new Date().toISOString().slice(0, 10);
  const perTurn = latencyMs ? `${(latencyMs / 10000).toFixed(1)}s/turn (${(latencyMs / 1000).toFixed(0)}s total)` : "— (scored --no-run)";
  return `## ${model} — screened ${dateStr}
TIER: ${s.tier}   |   objective ${s.objective}/100

GATES
  uncensored ......... ${s.willingnessPass ? "PASS" : `⚠ REVIEW (${s.refus}/${s.gateDen} narrator-voice refusal markers — confirm in-session)`}
  location routing ... ${s.locGate ? "PASS" : "FAIL"} (${s.locDen - s.locErr}/${s.locDen} correct)  [hard gate]
SCORED
  restraint (no-op) .. ${bar(s.restraint)} ${s.statFPden - s.statFP}/${s.statFPden} turns stayed empty
  stat direction ..... ${bar(s.statDir)} ${s.vigOk}/${s.vigDen} Vigor↓ on combat/injury
  choices format ..... ${bar(s.format)} ${s.chOk}/${s.chDen} clean option blocks
  prose .............. — (fill in-session: read the dump)
  latency ............ ${perTurn}`;
}

function updateBoard(s) {
  const dateStr = new Date().toISOString().slice(0, 10);
  const board = existsSync(BOARD_JSON) ? JSON.parse(readFileSync(BOARD_JSON, "utf8")) : [];
  const rec = { model, date: dateStr, tier: s.tier, objective: s.objective,
    restraint: Math.round(s.restraint), statDir: Math.round(s.statDir), format: Math.round(s.format), locAcc: Math.round(s.locAcc), refusals: s.refus };
  const next = board.filter((r) => r.model !== model).concat(rec);
  const rank = (t) => t === "S" ? 0 : t === "A" ? 1 : t === "B" ? 2 : t === "C" ? 3 : 4;
  next.sort((a, b) => rank(a.tier) - rank(b.tier) || b.objective - a.objective);
  writeFileSync(BOARD_JSON, JSON.stringify(next, null, 2), "utf8");
  const rows = next.map((r) => `| ${r.model} | ${r.tier} | ${r.objective} | ${r.restraint} | ${r.statDir} | ${r.format} | ${r.locAcc}% | ${r.refusals} | ${r.date} |`).join("\n");
  const md = `# Model screen leaderboard

Auto-generated by \`npm run screen -- --model <label>\` (gate world, shipped default prompts). Objective score
weights restraint 35 / stat-direction 30 / choices-format 35. Location routing is the one hard gate; refusal
markers are a ⚠ review flag (confirm in-session). Prose is judged separately in-session.

**One run per model (n=1)** — tiers are directional, and restraint is the noisiest axis. Re-screen or run the
full \`gateA\`/\`gateB\` matrix at \`--repeat 3\` before a decision that matters. Method: [GATE-PROBE.md](GATE-PROBE.md).

| Model | Tier | Obj | Restraint | StatDir | Format | LocAcc | Refusals | Screened |
|---|---|---|---|---|---|---|---|---|
${rows}
`;
  writeFileSync(BOARD_MD, md, "utf8");
}

const latencyMs = fileArg || noRun ? null : await runBaseline();
const dump = fileArg ? path.resolve(fileArg) : newestDump();
const s = score(dump);
console.log("\n" + card(s, latencyMs) + "\n");
updateBoard(s);
console.log(`→ leaderboard updated: ${path.relative(REPO_ROOT, BOARD_MD)}`);
