import { afterEach, expect, it, vi } from 'vitest';
import { render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { TooltipProvider } from '@/components/ui/tooltip';
import { canvasHistoryFor } from '@/lib/canvasHistory';
import { LocationsCanvasReference } from './LocationsCanvasReference';

afterEach(() => vi.restoreAllMocks());

it('keeps canvas preferences and history local across fullscreen edits and remounts', async () => {
  const user = userEvent.setup();
  localStorage.setItem('FORMAMORPH_canvasSnap', 'false');
  const savedHistory = canvasHistoryFor('authored-world');
  savedHistory.current = { past: [{ slice: 'locations', before: [], after: [] }], future: [] };
  const read = vi.spyOn(Storage.prototype, 'getItem');
  const write = vi.spyOn(Storage.prototype, 'setItem');
  const show = () => render(<TooltipProvider><LocationsCanvasReference /></TooltipProvider>);
  const first = show();
  await user.click(screen.getByRole('button', { name: 'Edit Full Screen' }));
  expect(await screen.findByRole('toolbar', { name: 'Canvas Tools' })).toBeInTheDocument();
  expect(screen.getByRole('button', { name: 'Undo' })).toBeDisabled();
  expect(screen.getByRole('button', { name: 'Redo' })).toBeDisabled();
  const snap = screen.getByRole('button', { name: 'Snap To Grid' });
  expect(snap).toHaveAttribute('aria-pressed', 'true');
  await user.click(snap);
  expect(snap).toHaveAttribute('aria-pressed', 'false');
  await user.click(screen.getByRole('button', { name: 'Show Grid' }));
  expect(screen.getByRole('button', { name: 'Show Grid' })).toHaveAttribute('aria-pressed', 'false');
  await user.click(screen.getByRole('button', { name: 'Auto Arrange All' }));
  expect(screen.getByRole('button', { name: 'Undo' })).toBeEnabled();
  await user.click(screen.getByRole('button', { name: 'Undo' }));
  expect(screen.getByRole('button', { name: 'Redo' })).toBeEnabled();
  await user.click(screen.getByRole('button', { name: 'Redo' }));
  expect(screen.getByRole('button', { name: 'Undo' })).toBeEnabled();
  first.unmount();
  const second = show();
  expect(screen.getByLabelText('Selected Location')).toHaveTextContent('(20, 60)');
  await user.click(screen.getByRole('button', { name: 'Edit Full Screen' }));
  expect(await screen.findByRole('button', { name: 'Undo' })).toBeDisabled();
  expect(screen.getByRole('button', { name: 'Snap To Grid' })).toHaveAttribute('aria-pressed', 'true');
  expect(screen.getByRole('button', { name: 'Show Grid' })).toHaveAttribute('aria-pressed', 'true');
  expect(canvasHistoryFor('authored-world')).toBe(savedHistory);
  expect(savedHistory.current.past).toHaveLength(1);
  expect(read).not.toHaveBeenCalled();
  expect(write).not.toHaveBeenCalled();
  second.unmount();
});
